name: flutmovie
description: A flutter boilder plate which implements DDD principles.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # google translator
  translator: ^0.1.5
  
  # bloc is for state managment
  flutter_bloc: ^6.0.0
  bloc: ^6.0.0
  equatable: ^1.2.0
  
  # dio is for api/network connections
  dio: ^3.0.9

  # flushbar is for showing message on screen
  flushbar: ^1.10.4

  # shared_preferences is for storing data on local
  shared_preferences: ^0.5.8

  #get_it is for dependency injection
  get_it: ^4.0.4

  # injectable is for code generation 
  injectable: ^1.0.4

  # sembast is for create db on local
  sembast: ^2.4.7+4
  
  # path_provider is for getting application path from device.
  path_provider: ^1.6.11

  # google_fonts is for installing google fonts from the internet easly.
  google_fonts: ^1.1.0

  # dartz is for using Either class
  dartz: ^0.9.1

  # connectivity is for checking if device connected to the internet
  connectivity: ^0.4.9

dependency_overrides:
  analyzer: '0.39.14'    
  build_resolvers: '1.3.10'

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # build_runner, injectable_generator is for code generation
  build_runner:
  injectable_generator: ^1.0.4


  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lang/en.json
    - assets/lang/tr.json
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #fonts:
  #  - family: Flamenco
  #    fonts:
  #      - asset: assets/fonts/Flamenco-Regular.ttf
  #      - asset: assets/fonts/Flamenco-Light.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
